name: $(Date:yyyyMMdd).$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'
  container: ubuntu:16.04

  steps:
    - script: printenv