version: "3"

tasks:
  categorize-images:
    desc: Categorize Images in the directory 'categorize-images/all_images/input'
    cmds:
      - uv run main.py
    dir: categorize-images

  get-missing:
    desc: Get missing images in 'categorize-images/all_images/output'
    cmds:
      - uv run generate_tree.py --only-missing
    dir: categorize-images
    
  crop-images:
    desc: Crop images in 'categorize-images/all_images/output'
    cmds:
      - uv run main.py
    dir: image-manipulation
