version: "3"

tasks:
  process:
    desc: Process all images in 'categorize-images/all_images/input'
    cmds:
      - task: categorize-images
      - task: crop-images

  categorize-images:
    desc: Categorize Images in the directory 'categorize-images/all_images/input'
    cmds:
      - uv run main.py
    dir: categorize-images

  crop-images:
    desc: Crop images in 'categorize-images/all_images/output'
    cmds:
      - uv run main.py
    dir: image-manipulation

  get-missing:
    desc: Get missing images in 'categorize-images/all_images/output'
    cmds:
      - uv run generate_tree.py --only-missing
    dir: categorize-images
