service: rekognition-analysis-s3-image

frameworkVersion: ">=1.10.0"

custom:
  alerts:
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: countrypeaches@gmail.com
        alarms:
          - functionErrors
  bucket: dark-cloud-bucket-${self:provider.stage}

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 10
  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::dark-cloud-bucket-${self:provider.stage}"

package:
 include:
   - categorize/**

functions:
  imageAnalysis:
    handler: categorize.categorize_and_move_image
    events:
      - existingS3:
          bucket: dark-cloud-bucket-${self:provider.stage}
          events: 
            - s3:ObjectCreated:*
          rules:
            - prefix: archive/
    environment:
      project: dark-cloud
      stage: ${self:provider.stage}
resources:
 Resources:
   NewResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: dark-cloud-bucket-${self:provider.stage}

plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
  - serverless-plugin-aws-alerts
