apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: raboley/dark-cloud-website:86
        ports:
        - containerPort: 80

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: flask-handler
  name: flask-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      run: flask-handler
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flask-handler
    spec:
      containers:
      - name: flask-handler
        image: raboley/flask-handler:latest
        ports:
        - containerPort: 5001
        resources: {}
status: {}

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: flask-books
  name: flask-books
spec:
  replicas: 2
  selector:
    matchLabels:
      run: flask-books
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flask-books
    spec:
      containers:
      - name: flask-books
        image: raboley/flask-books:latest
        ports:
        - containerPort: 5000
status: {}