---

- name: get Dynatrace auth token
  shell: wget  -O Dynatrace-OneAgent-Linux-1.159.273.sh "https://hvt80926.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=dxN-cpcLQIy6VmWwhtN22&arch=x86&flavor=default"
  sudo: true
  sudo_user: root

- name: get Dynatrace auth token
  shell: "wget https://ca.dynatrace.com/dt-root.cert.pem ; ( echo 'Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="--SIGNED-INSTALLER"'; echo ; echo ; echo '----SIGNED-INSTALLER' ; cat Dynatrace-OneAgent-Linux-1.159.273.sh ) | openssl cms -verify -CAfile dt-root.cert.pem > /dev/null"
  sudo: true
  sudo_user: root

- name: get Dynatrace auth token
  shell: " /bin/sh Dynatrace-OneAgent-Linux-1.159.273.sh  APP_LOG_CONTENT_ACCESS=1 INFRA_ONLY=0"
  sudo: true
  sudo_user: root
