---
# This playbook deploys a simple kubeadm install.
- name: Bootstrap Tasks
  hosts: 
    - master
    - worker
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: False
  roles:
    - common
    #- dynatrace

- name: Install Kubernetes master
  hosts: master
  remote_user: "{{ ansible_remote_user }}"
  become: yes
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - master
    #- contiv
    - calico

- name: Install nodes
  remote_user: "{{ ansible_remote_user }}"
  hosts: worker
  become: yes
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - worker

# - name: Deploy App
#   remote_user: "{{ ansible_remote_user }}"
#   hosts: master
#   become: yes
#   become_method: sudo
#   roles:
#     - deploy_app

    # - import_playbook: deploy_contiv_network_config.yml
# - import_playbook: deploy_istio.yml
# - import_playbook: deploy_sample_apps.yml

