resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.15'
  inputs:
    versionSpec: 10.15

    checkLatest: true


- task: Npm@1
  displayName: 'npm install angular cli'
  inputs:
    command: custom

    verbose: false

    customCommand: 'install @angular/cli -g'


- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false


- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom

    verbose: false

    customCommand: 'run build'


- task: DockerCompose@0
  displayName: 'Docker compose build'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'dark-cloud-encyclopedia'

    dockerComposeFile: '**/docker-compose.prod.yml'

    dockerComposeCommand: build


- task: DockerCompose@0
  displayName: 'Docker compose push'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'dark-cloud-encyclopedia'

    dockerComposeFile: '**/docker-compose.prod.yml'

    dockerComposeCommand: push



