name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "10.15.3"

      - name: Install Angular CLI
        run: npm install -g @angular/cli@7.0.3

      - name: Install dependencies
        run: npm install
        working-directory: ./dark-cloud-website

      - name: Build the website
        run: npm run build -- --prod
        working-directory: ./dark-cloud-website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dark-cloud-website/dist/APM
